# Generated by Django 4.2.5 on 2024-03-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('imgPath', models.CharField(max_length=255)),
                ('durations', models.IntegerField()),
                ('genre', models.TextField()),
                ('language', models.CharField(max_length=255)),
                ('mpaaRatingType', models.CharField(max_length=255)),
                ('mpaaRatingLabel', models.CharField(max_length=255)),
                ('userRating', models.IntegerField()),
            ],
        ),
    ]
